// ---------- headers ----------
#ifdef __APPLE__
// defined before OpenGL and GLUT includes to avoid deprecation messages
#define GL_SILENCE_DEPRECATION
#include <OpenGL/gl.h>
#include <GLUT/glut.h>      // handle the window-managing operations
#else
#include <GL/glew.h>
#include <GL/freeglut.h>    // handle the window-managing operations
#endif
#include <stdlib.h>
#include <iostream>
#include <cmath>
// playsound library
#include <windows.h>
#include <mmsystem.h>
#pragma comment(lib, "winmm.lib")

using namespace std;

// ---------- global variables ----------
GLint win_width = 500,
win_hight = 500;
GLdouble PI = 3.14159265359;

int scene = 1;
int score = 0;
int sceneState = 0;

// scene1
float scene1GirlMoveX = 0.0f;
float scene1GrandmaMoveX = 0.0f;
float scene1CarMoveY = 0.0f;
// scene2
float scene2GirlMoveX = 0.0f;
float scene2BalloonMoveY = 0.0f;
float scene2GirlJumpY = 0.0f;
float scene2GiveBalloonX = 0.0f;
int scene2HelpStep = 0;
// 0= jump and take balloon
// 1= go to boy
// 2= give balloon to boy
// 3= girl leaves
// scene3
float scene3GirlMoveX = 0.0f;
float scene3CatMoveX = 0.0f;
float scene3CatMoveY = 0.0f;
int scene3Step = 0;
// scene 4
float scene4GirlMoveX = 0.0f;
float scene4MysteryMoveX = 0.0f;
// scene 5
float scene5GirlMoveX = 0.0f;
float scene5MysteryMoveX = 0.0f;
// wait timing
int waitStartTime = 0;
bool waitStarted = false;

// scene1
bool grandmaHelped = false;
// scene2
bool kidHelped = false;
// scene3
bool catSatDown = false;
// sounds
static bool carSoundPlayed = false;
static bool cryPlayed = false;
static bool meowPlayed = false;

float badBtnX1 = -0.90f, badBtnX2 = -0.10f;
float goodBtnX1 = 0.10f, goodBtnX2 = 0.90f;
float btnY1 = -0.92f, btnY2 = -0.76f;

GLuint myTexture1, myTexture2;
char image1Path[] = "C:\\textures\\brickwall.bmp";
char image2Path[] = "C:\\textures\\road.bmp";

// ---------- helper functions ----------

/**
 * waits for a number of seconds using the real elapsed time from GLUT.
 *
 * @param seconds number of seconds to wait before returning true.
 * @return true if the waiting time is finished, false if it is still waiting.
 *
 * source: https://www.opengl.org/resources/libraries/glut/spec3/node70.html
 * source: https://stackoverflow.com/questions/5357119/constant-game-speed-independent-of-variable-fps-in-opengl-with-glut
 */
bool waitForSeconds(float seconds)
{
    if (!waitStarted)
    {
        waitStartTime = glutGet(GLUT_ELAPSED_TIME);
        waitStarted = true;
    }

    int currentTime = glutGet(GLUT_ELAPSED_TIME);
    int waitTime = seconds * 1000;

    if (currentTime - waitStartTime >= waitTime)
    {
        waitStarted = false;
        return true;
    }

    return false;
}

/**
 * draws a filled circle using the triangle fan method.
 * source: https://gist.github.com/linusthe3rd/803118
 *
 * @param x center x position of the circle.
 * @param y center y position of the circle.
 * @param radius circle radius.
 * @return nothing, it only sends vertices to OpenGL.
 */
void drawFilledCircle(GLfloat x, GLfloat y, GLfloat radius) {
    int i;
    int triangleAmount = 20; // number of triangles used to draw circle

    // GLfloat radius = 0.8f; // radius
    GLfloat twicePi = 2.0f * PI;

    glBegin(GL_TRIANGLE_FAN);
    glVertex2f(x, y); // center point
    for (i = 0; i <= triangleAmount; i++) {
        glVertex2f(
            x + (radius * cos(i * twicePi / triangleAmount)),
            y + (radius * sin(i * twicePi / triangleAmount))
        );
    }
    glEnd();
}

/**
 * draws an outlined circle using the line loop method.
 * source: https://gist.github.com/linusthe3rd/803118
 *
 * @param x center x position of the circle.
 * @param y center y position of the circle.
 * @param radius circle radius.
 * @return nothing, it only draws the circle outline.
 */
void drawHollowCircle(GLfloat x, GLfloat y, GLfloat radius) {
    int i;
    int lineAmount = 100; // number of lines used to draw circle

    // GLfloat radius = 0.8f; // radius
    GLfloat twicePi = 2.0f * PI;

    glBegin(GL_LINE_LOOP);
    for (i = 0; i <= lineAmount; i++) {
        glVertex2f(
            x + (radius * cos(i * twicePi / lineAmount)),
            y + (radius * sin(i * twicePi / lineAmount))
        );
    }
    glEnd();
}

/**
 * loads a bmp image file and creates an OpenGL texture from it.
 * source: http://stackoverflow.com/questions/12518111/how-to-load-a-bmp-on-glut-to-use-it-as-a-texture
 *
 * @param filename path of the bmp file that will be loaded.
 * @param width image width in pixels.
 * @param height image height in pixels.
 * @return the texture id generated by OpenGL.
 */
GLuint LoadTexture(const char* filename, int width, int height)
{
    GLuint texture;
    unsigned char* data;

    // reads the raw image file
    FILE* file;
    // file = fopen(filename, "rb");
    fopen_s(&file, filename, "rb");

    if (file == NULL)
    {
        cout << "Unable to open the image file" << endl << "Program will exit :(" << endl;
        exit(0);
        return 0;
    }

    data = (unsigned char*)malloc(width * height * 3);
    fread(data, width * height * 3, 1, file);

    fclose(file);

    // reorder the image colors to RGB not BGR
    for (int i = 0; i < width * height; ++i)
    {
        int index = i * 3;
        unsigned char B, R;
        B = data[index];
        R = data[index + 2];

        data[index] = R;
        data[index + 2] = B;

    }

    // texture setup
    glGenTextures(1, &texture); // generate the texture with the loaded data
    glBindTexture(GL_TEXTURE_2D, texture); // bind the texture to it's array

    glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE); // set texture environment parameters GL_REPLACE GL_MODULATE

    glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);

    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, width, height, 0, GL_RGB, GL_UNSIGNED_BYTE, data);

    free(data); // free the texture array

    if (glGetError() != GL_NO_ERROR)
        printf("GLError in genTexture()\n");

    return texture; // return whether it was successfull
}

/**
 * draws a simple filled rectangle using four corner points.
 *
 * @param x1 left x coordinate.
 * @param y1 bottom y coordinate.
 * @param x2 right x coordinate.
 * @param y2 top y coordinate.
 * @return nothing, it draws directly on the screen.
 */
void drawQuad(float x1, float y1, float x2, float y2)
{
    glBegin(GL_QUADS);
    glVertex2f(x1, y1);
    glVertex2f(x2, y1);
    glVertex2f(x2, y2);
    glVertex2f(x1, y2);
    glEnd();
}

/**
 * draws a colored rectangle with a black outline around it.
 *
 * @param x1 left x coordinate.
 * @param y1 bottom y coordinate.
 * @param x2 right x coordinate.
 * @param y2 top y coordinate.
 * @param r red color value.
 * @param g green color value.
 * @param b blue color value.
 * @return nothing, it draws the rectangle and its border.
 */
void drawRectWithOutline(float x1, float y1, float x2, float y2,
    float r, float g, float b)
{
    glColor3f(r, g, b);
    drawQuad(x1, y1, x2, y2);

    glColor3f(0.0f, 0.0f, 0.0f);
    glLineWidth(2.0f);
    glBegin(GL_LINE_LOOP);
    glVertex2f(x1, y1);
    glVertex2f(x2, y1);
    glVertex2f(x2, y2);
    glVertex2f(x1, y2);
    glEnd();
}

/**
 * draws one straight line between two points.
 *
 * @param x1 start x coordinate.
 * @param y1 start y coordinate.
 * @param x2 end x coordinate.
 * @param y2 end y coordinate.
 * @return nothing, it draws directly with OpenGL lines.
 */
void drawLine(float x1, float y1, float x2, float y2)
{
    glBegin(GL_LINES);
    glVertex2f(x1, y1);
    glVertex2f(x2, y2);
    glEnd();
}

/**
 * draws a rectangle and covers it with the selected texture.
 *
 * @param x1 left x coordinate.
 * @param y1 bottom y coordinate.
 * @param x2 right x coordinate.
 * @param y2 top y coordinate.
 * @param texture OpenGL texture id used on the rectangle.
 * @return nothing, it only draws the textured shape.
 */
void drawTexturedRect(float x1, float y1, float x2, float y2, GLuint texture)
{
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, texture);

    glColor3f(1.0f, 1.0f, 1.0f);

    glBegin(GL_QUADS);
    glTexCoord2f(0.0f, 0.0f); glVertex2f(x1, y1);
    glTexCoord2f(1.0f, 0.0f); glVertex2f(x2, y1);
    glTexCoord2f(1.0f, 1.0f); glVertex2f(x2, y2);
    glTexCoord2f(0.0f, 1.0f); glVertex2f(x1, y2);
    glEnd();

    glBindTexture(GL_TEXTURE_2D, 0);
    glDisable(GL_TEXTURE_2D);

    glColor3f(1.0f, 1.0f, 1.0f);
}

/**
 * draws a small sun object in the background.
 *
 * @param x x position of the sun.
 * @param y y position of the sun.
 * @param scale size multiplier for the whole sun.
 * @return nothing, it draws the sun in the current scene.
 */
void drawSun(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    glColor3f(1.0f, 0.60f, 0.0f);
    drawFilledCircle(0.0f, 0.0f, 0.16f);

    glColor3f(1.0f, 0.85f, 0.0f);
    drawFilledCircle(0.0f, 0.0f, 0.12f);

    glPopMatrix();
}

/**
 * draws a cloud made from overlapping circles.
 *
 * @param x x position of the cloud.
 * @param y y position of the cloud.
 * @param scale size multiplier for the cloud.
 * @return nothing, it draws the cloud in place.
 */
void drawCloud(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    glColor3f(1.0f, 1.0f, 1.0f);
    drawFilledCircle(0.0f, 0.0f, 0.11f);
    drawFilledCircle(0.10f, 0.04f, 0.09f);
    drawFilledCircle(-0.10f, 0.04f, 0.09f);
    drawFilledCircle(0.20f, 0.0f, 0.08f);

    glPopMatrix();
}

/**
 * draws a tree with a trunk and rounded leaves.
 *
 * @param x x position of the tree.
 * @param y y position of the tree.
 * @param scale size multiplier for the tree.
 * @param leafR red value for the leaves color.
 * @param leafG green value for the leaves color.
 * @param leafB blue value for the leaves color.
 * @return nothing, it draws the tree directly.
 */
void drawTree(float x, float y, float scale,
    float leafR, float leafG, float leafB)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // trunk
    drawRectWithOutline(-0.05f, 0.0f, 0.05f, 0.40f,
        0.54f, 0.27f, 0.07f);

    // leaves
    glColor3f(leafR, leafG, leafB);
    drawFilledCircle(0.0f, 0.50f, 0.15f);
    drawFilledCircle(-0.12f, 0.45f, 0.12f);
    drawFilledCircle(0.12f, 0.45f, 0.12f);
    drawFilledCircle(0.0f, 0.62f, 0.12f);

    glPopMatrix();
}

/**
 * draws the car used in the street scene.
 *
 * @param x x position of the car.
 * @param y y position of the car.
 * @param scale size multiplier for the car.
 * @return nothing, it draws the car parts together.
 */
void drawCar(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // wheels first
    glColor3f(0.0f, 0.0f, 0.0f);
    drawFilledCircle(-0.22f, -0.05f, 0.06f);
    drawFilledCircle(0.22f, -0.05f, 0.06f);

    // window
    drawRectWithOutline(-0.23f, 0.20f, 0.23f, 0.36f,
        0.0f, 0.75f, 1.0f);

    // body
    drawRectWithOutline(-0.32f, -0.02f, 0.32f, 0.20f,
        1.0f, 0.0f, 0.0f);

    // lights
    glColor3f(1.0f, 0.84f, 0.0f);
    drawFilledCircle(-0.22f, 0.08f, 0.035f);
    drawFilledCircle(0.22f, 0.08f, 0.035f);

    glPopMatrix();
}

/**
 * draws the bench object used in the park scenes.
 *
 * @return nothing, it draws the bench at the current model position.
 */
void drawBench()
{
    // backrest
    drawRectWithOutline(-0.15f, 0.10f, 0.55f, 0.45f,
        0.65f, 0.45f, 0.35f);

    // seat
    drawRectWithOutline(-0.15f, 0.00f, 0.55f, 0.15f,
        0.55f, 0.35f, 0.25f);

    // legs
    drawRectWithOutline(-0.15f, -0.15f, -0.10f, 0.00f,
        0.35f, 0.20f, 0.10f);

    drawRectWithOutline(0.50f, -0.15f, 0.55f, 0.00f,
        0.35f, 0.20f, 0.10f);
}

/**
 * draws a balloon with a string and small highlight.
 *
 * @param x x position of the balloon.
 * @param y y position of the balloon.
 * @param scale size multiplier for the balloon.
 * @return nothing, it draws the balloon object.
 */
void drawBalloon(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    glColor3f(0.0f, 0.0f, 0.0f);
    glLineWidth(2.0f);
    drawLine(0.0f, -0.35f, 0.0f, -0.03f);

    glColor3f(1.0f, 0.0f, 0.0f);
    drawFilledCircle(0.0f, 0.05f, 0.08f);

    glColor3f(1.0f, 0.80f, 0.80f);
    drawFilledCircle(0.03f, 0.08f, 0.02f);

    glColor3f(0.0f, 0.0f, 0.0f);
    drawHollowCircle(0.0f, 0.05f, 0.08f);

    glPopMatrix();
}

/**
 * draws a small football object.
 *
 * @param x x position of the ball.
 * @param y y position of the ball.
 * @param scale size multiplier for the ball.
 * @return nothing, it draws the football shape.
 */
void drawFootball(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    glColor3f(1.0f, 1.0f, 1.0f);
    drawFilledCircle(0.0f, 0.0f, 0.10f);

    glColor3f(0.0f, 0.0f, 0.0f);
    drawHollowCircle(0.0f, 0.0f, 0.10f);
    drawFilledCircle(0.0f, 0.0f, 0.03f);
    drawFilledCircle(0.05f, 0.05f, 0.018f);
    drawFilledCircle(-0.05f, 0.05f, 0.018f);
    drawFilledCircle(0.05f, -0.05f, 0.018f);
    drawFilledCircle(-0.05f, -0.05f, 0.018f);

    glPopMatrix();
}

/**
 * draws a small water puddle on the ground.
 *
 * @param x x position of the puddle.
 * @param y y position of the puddle.
 * @param scale size multiplier for the puddle.
 * @return nothing, it draws the puddle effect.
 */
void drawWaterPuddle(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // main water shape
    glColor4f(0.0f, 0.65f, 0.90f, 0.70f);
    drawFilledCircle(-0.05f, 0.00f, 0.06f);
    drawFilledCircle(0.05f, -0.03f, 0.05f);
    drawFilledCircle(0.00f, -0.02f, 0.07f);

    glPopMatrix();
}

/**
 * draws the trash can object with lid, handles, and trash pieces.
 *
 * @param x x position of the trash can.
 * @param y y position of the trash can.
 * @param scale size multiplier for the trash can.
 * @return nothing, it draws the full trash can object.
 */
void drawTrashCan(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // bin body
    glColor3f(0.18f, 0.25f, 0.20f);
    drawQuad(-0.10f, -0.18f, 0.10f, 0.15f);

    // lid
    glColor3f(0.12f, 0.18f, 0.14f);
    drawQuad(-0.13f, 0.15f, 0.13f, 0.21f);

    // side handles
    glColor3f(0.10f, 0.12f, 0.10f);
    drawQuad(-0.14f, 0.00f, -0.10f, 0.08f);
    drawQuad(0.10f, 0.00f, 0.14f, 0.08f);

    // garbage inside the bin - 3 pieces
    drawRectWithOutline(-0.08f, 0.22f, -0.04f, 0.28f,
        0.90f, 0.10f, 0.10f);

    drawRectWithOutline(-0.01f, 0.22f, 0.03f, 0.29f,
        0.95f, 0.85f, 0.10f);

    drawRectWithOutline(0.05f, 0.22f, 0.09f, 0.27f,
        0.10f, 0.20f, 0.85f);

    // vertical details
    glColor3f(0.28f, 0.35f, 0.30f);
    glLineWidth(2.0f);
    glBegin(GL_LINES);
    glVertex2f(-0.05f, -0.18f);
    glVertex2f(-0.05f, 0.15f);

    glVertex2f(0.0f, -0.18f);
    glVertex2f(0.0f, 0.15f);

    glVertex2f(0.05f, -0.18f);
    glVertex2f(0.05f, 0.15f);
    glEnd();

    // outline body
    glColor3f(0.0f, 0.0f, 0.0f);
    glLineWidth(2.0f);

    glBegin(GL_LINE_LOOP);
    glVertex2f(-0.10f, -0.18f);
    glVertex2f(0.10f, -0.18f);
    glVertex2f(0.10f, 0.15f);
    glVertex2f(-0.10f, 0.15f);
    glEnd();

    // outline lid
    glBegin(GL_LINE_LOOP);
    glVertex2f(-0.13f, 0.15f);
    glVertex2f(0.13f, 0.15f);
    glVertex2f(0.13f, 0.21f);
    glVertex2f(-0.13f, 0.21f);
    glEnd();

    // outline handles
    glBegin(GL_LINE_LOOP);
    glVertex2f(-0.14f, 0.00f);
    glVertex2f(-0.10f, 0.00f);
    glVertex2f(-0.10f, 0.08f);
    glVertex2f(-0.14f, 0.08f);
    glEnd();

    glBegin(GL_LINE_LOOP);
    glVertex2f(0.10f, 0.00f);
    glVertex2f(0.14f, 0.00f);
    glVertex2f(0.14f, 0.08f);
    glVertex2f(0.10f, 0.08f);
    glEnd();

    glPopMatrix();
}

/**
 * draws one small trash piece with a selected color.
 *
 * @param x x position of the trash piece.
 * @param y y position of the trash piece.
 * @param scale size multiplier for the trash piece.
 * @param r red color value.
 * @param g green color value.
 * @param b blue color value.
 * @return nothing, it draws one small trash item.
 */
void drawTrashPiece(float x, float y, float scale,
    float r, float g, float b)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    drawRectWithOutline(-0.04f, -0.04f, 0.04f, 0.04f,
        r, g, b);

    glPopMatrix();
}

/**
 * writes text on the screen using GLUT bitmap characters.
 * source: text in OpenGL by Prof. David Bernstein.
 * https://users.cs.jmu.edu/bernstdh/web/common/lectures/summary_opengl-text.php
 *
 * @param x x position where the text starts.
 * @param y y position where the text starts.
 * @param text the message that will be displayed.
 * @return nothing, it prints the text on the OpenGL window.
 */
void drawText(float x, float y, const char* text)
{
    glRasterPos2f(x, y);

    for (int i = 0; text[i] != '\0'; i++) {
        glutBitmapCharacter(GLUT_BITMAP_TIMES_ROMAN_24, text[i]);
    }
}

/**
 * draws one clickable button with a label inside it.
 *
 * @param x1 left x coordinate of the button.
 * @param y1 bottom y coordinate of the button.
 * @param x2 right x coordinate of the button.
 * @param y2 top y coordinate of the button.
 * @param r red color value for the button.
 * @param g green color value for the button.
 * @param b blue color value for the button.
 * @param label text shown inside the button.
 * @return nothing, it draws the button and its label.
 */
void drawButton(float x1, float y1, float x2, float y2,
    float r, float g, float b, const char* label)
{
    drawRectWithOutline(x1, y1, x2, y2, r, g, b);

    glColor3f(1.0f, 1.0f, 1.0f);

    int len = 0;
    while (label[len] != '\0')
        len++;

    float textX = (x1 + x2) / 2.0f - (len * 0.022f);
    float textY = (y1 + y2) / 2.0f - 0.025f;

    drawText(textX, textY, label);
}

/**
 * draws the two choice buttons used in the story decisions.
 *
 * @param badLabel text shown on the bad choice button.
 * @param goodLabel text shown on the good choice button.
 * @return nothing, it draws both buttons on the screen.
 */
void drawChoiceButtons(const char* badLabel, const char* goodLabel)
{
    drawButton(badBtnX1, btnY1, badBtnX2, btnY2,
        0.75f, 0.15f, 0.15f, badLabel);

    drawButton(goodBtnX1, btnY1, goodBtnX2, btnY2,
        0.15f, 0.60f, 0.22f, goodLabel);
}

/**
 * draws dialogue text inside a semi-transparent black box.
 *
 * @param x1 left x coordinate of the box.
 * @param y1 bottom y coordinate of the box.
 * @param x2 right x coordinate of the box.
 * @param y2 top y coordinate of the box.
 * @param line1 first dialogue line.
 * @param line2 second dialogue line, use NULL if there is no second line.
 * @return nothing, it draws the dialogue box and the text.
 */
void drawDialogueBox(float x1, float y1, float x2, float y2,
    const char* line1, const char* line2)
{
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

    // semi-transparent black background
    glColor4f(0.0f, 0.0f, 0.0f, 0.65f);
    drawQuad(x1, y1, x2, y2);

    // white border
    glColor3f(1.0f, 1.0f, 1.0f);
    glLineWidth(2.0f);
    glBegin(GL_LINE_LOOP);
    glVertex2f(x1, y1);
    glVertex2f(x2, y1);
    glVertex2f(x2, y2);
    glVertex2f(x1, y2);
    glEnd();

    // white text
    glColor3f(1.0f, 1.0f, 1.0f);

    if (line2 == NULL)
    {
        drawText(x1 + 0.04f, y1 + 0.08f, line1);
    }
    else
    {
        drawText(x1 + 0.04f, y1 + 0.14f, line1);
        drawText(x1 + 0.04f, y1 + 0.04f, line2);
    }
}


// ---------- characters ----------

/**
 * draws the main girl character of the story.
 *
 * @param x x position of the girl.
 * @param y y position of the girl.
 * @param scale size multiplier for the girl.
 * @return nothing, it draws the full character.
 */
void drawMainGirl(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // neck
    glColor3f(0.85f, 0.70f, 0.45f);
    drawQuad(-0.02f, 0.35f, 0.02f, 0.45f);

    // face
    glColor3f(0.85f, 0.70f, 0.45f);
    drawFilledCircle(0.0f, 0.50f, 0.13f);

    // hair circles
    glColor3f(0.25f, 0.05f, 0.0f);
    drawFilledCircle(-0.11f, 0.65f, 0.10f);
    drawFilledCircle(0.11f, 0.65f, 0.10f);

    // hair middle rectangle
    drawQuad(-0.10f, 0.58f, 0.10f, 0.66f);

    // hair middle triangle
    glBegin(GL_TRIANGLES);
    glVertex2f(-0.11f, 0.61f);
    glVertex2f(0.11f, 0.61f);
    glVertex2f(0.0f, 0.54f);
    glEnd();

    // hair slanted rectangles
    glBegin(GL_QUADS);

    // left slanted rectangle
    glVertex2f(-0.20f, 0.52f);
    glVertex2f(-0.16f, 0.48f);
    glVertex2f(-0.04f, 0.64f);
    glVertex2f(-0.08f, 0.68f);

    // right slanted rectangle
    glVertex2f(0.20f, 0.52f);
    glVertex2f(0.16f, 0.48f);
    glVertex2f(0.04f, 0.64f);
    glVertex2f(0.08f, 0.68f);

    glEnd();

    // eyes
    glColor3f(0.35f, 0.20f, 0.05f);
    drawFilledCircle(-0.05f, 0.50f, 0.018f);
    drawFilledCircle(0.05f, 0.50f, 0.018f);

    // mouth
    glColor3f(0.0f, 0.0f, 0.0f);
    glLineWidth(2.5f);
    drawLine(-0.04f, 0.44f, 0.04f, 0.44f);

    // dress shoulders
    glColor3f(0.85f, 0.53f, 0.65f);
    drawFilledCircle(-0.09f, 0.30f, 0.07f);
    drawFilledCircle(0.09f, 0.30f, 0.07f);

    // dress body
    glBegin(GL_POLYGON);
    glVertex2f(-0.10f, 0.35f);
    glVertex2f(0.10f, 0.35f);
    glVertex2f(0.22f, -0.20f);
    glVertex2f(-0.22f, -0.20f);
    glEnd();

    // arms
    glColor3f(0.85f, 0.70f, 0.45f);

    drawQuad(-0.15f, 0.05f, -0.11f, 0.25f);
    drawFilledCircle(-0.13f, 0.03f, 0.035f);

    drawQuad(0.11f, 0.05f, 0.15f, 0.25f);
    drawFilledCircle(0.13f, 0.03f, 0.035f);

    // legs
    drawQuad(-0.07f, -0.30f, -0.03f, -0.20f);
    drawQuad(0.03f, -0.30f, 0.07f, -0.20f);

    // shoes
    glColor3f(0.80f, 0.55f, 0.65f);
    drawFilledCircle(-0.05f, -0.32f, 0.04f);
    drawFilledCircle(0.05f, -0.32f, 0.04f);

    glColor3f(0.70f, 0.45f, 0.35f);
    drawQuad(-0.09f, -0.38f, -0.01f, -0.34f);
    drawQuad(0.01f, -0.38f, 0.09f, -0.34f);

    glPopMatrix();
}

/**
 * draws the grandma character used in the first scene.
 *
 * @param x x position of the grandma.
 * @param y y position of the grandma.
 * @param scale size multiplier for the grandma.
 * @return nothing, it draws the full character.
 */
void drawGrandma(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // hair
    glColor3f(0.88f, 0.90f, 0.82f);
    drawFilledCircle(-0.10f, 0.58f, 0.06f);
    drawFilledCircle(0.10f, 0.58f, 0.06f);
    drawFilledCircle(-0.13f, 0.52f, 0.06f);
    drawFilledCircle(0.13f, 0.52f, 0.06f);
    drawFilledCircle(-0.14f, 0.47f, 0.06f);
    drawFilledCircle(0.14f, 0.47f, 0.06f);
    drawFilledCircle(0.0f, 0.62f, 0.09f);
    drawFilledCircle(-0.05f, 0.65f, 0.07f);
    drawFilledCircle(0.05f, 0.65f, 0.07f);

    // neck
    glColor3f(0.76f, 0.69f, 0.50f);
    drawQuad(-0.03f, 0.30f, 0.03f, 0.35f);

    // face
    drawFilledCircle(0.0f, 0.45f, 0.13f);

    // eyes
    glColor3f(0.0f, 0.0f, 0.0f);
    drawQuad(-0.08f, 0.47f, -0.02f, 0.50f);
    drawQuad(0.02f, 0.47f, 0.08f, 0.50f);

    // mouth
    glLineWidth(4.0f);
    glBegin(GL_LINE_STRIP);
    glVertex2f(-0.04f, 0.40f);
    glVertex2f(0.0f, 0.37f);
    glVertex2f(0.04f, 0.40f);
    glEnd();

    // Dress
    glColor3f(0.24f, 0.30f, 0.78f);
    drawFilledCircle(-0.12f, 0.28f, 0.09f);
    drawFilledCircle(0.12f, 0.28f, 0.09f);
    drawQuad(-0.18f, -0.40f, 0.18f, 0.32f);

    // arms
    glColor3f(0.76f, 0.69f, 0.50f);

    drawQuad(0.14f, 0.05f, 0.18f, 0.28f);
    drawFilledCircle(0.16f, 0.04f, 0.04f);

    drawQuad(-0.18f, 0.05f, -0.14f, 0.28f);
    drawFilledCircle(-0.16f, 0.04f, 0.04f);

    // bag
    glColor3f(1.0f, 0.90f, 0.0f);
    drawFilledCircle(-0.16f, -0.10f, 0.07f);

    glColor3f(0.0f, 0.0f, 0.0f);
    glLineWidth(3.0f);
    glBegin(GL_LINE_STRIP);
    glVertex2f(-0.19f, -0.04f);
    glVertex2f(-0.16f, 0.04f);
    glVertex2f(-0.13f, -0.04f);
    glEnd();

    // legs
    glColor3f(0.76f, 0.69f, 0.50f);
    drawQuad(-0.07f, -0.48f, -0.02f, -0.40f);
    drawQuad(0.02f, -0.48f, 0.07f, -0.40f);

    // shoes
    glColor3f(0.24f, 0.30f, 0.78f);
    drawFilledCircle(-0.05f, -0.48f, 0.045f);
    drawFilledCircle(0.05f, -0.48f, 0.045f);

    glColor3f(0.70f, 0.45f, 0.35f);
    drawQuad(-0.09f, -0.53f, -0.01f, -0.49f);
    drawQuad(0.01f, -0.53f, 0.09f, -0.49f);

    glPopMatrix();
}

/**
 * draws the boy character used in the balloon scene.
 *
 * @param x x position of the boy.
 * @param y y position of the boy.
 * @param scale size multiplier for the boy.
 * @return nothing, it draws the full character.
 */
void drawBoy(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // neck
    glColor3f(0.55f, 0.47f, 0.25f);
    drawQuad(-0.02f, 0.35f, 0.02f, 0.40f);

    // face
    drawFilledCircle(0.0f, 0.48f, 0.12f);

    // hair
    glColor3f(0.0f, 0.0f, 0.0f);
    glBegin(GL_TRIANGLES);
    glVertex2f(-0.14f, 0.55f);
    glVertex2f(-0.08f, 0.72f);
    glVertex2f(-0.02f, 0.55f);

    glVertex2f(-0.06f, 0.55f);
    glVertex2f(0.0f, 0.78f);
    glVertex2f(0.06f, 0.55f);

    glVertex2f(0.02f, 0.55f);
    glVertex2f(0.08f, 0.72f);
    glVertex2f(0.14f, 0.55f);
    glEnd();

    drawQuad(-0.11f, 0.50f, -0.08f, 0.60f);
    drawQuad(0.08f, 0.50f, 0.11f, 0.60f);
    drawQuad(-0.04f, 0.58f, 0.04f, 0.62f);

    // eyes
    glColor3f(0.70f, 1.0f, 0.20f);
    drawFilledCircle(-0.05f, 0.52f, 0.018f);
    drawFilledCircle(0.05f, 0.52f, 0.018f);

    // tear
    glColor3f(0.60f, 0.80f, 1.0f);
    drawFilledCircle(-0.06f, 0.48f, 0.015f);

    // mouth
    glColor3f(0.0f, 0.0f, 0.0f);
    glLineWidth(3.0f);
    glBegin(GL_LINE_STRIP);
    glVertex2f(-0.05f, 0.42f);
    glVertex2f(0.0f, 0.44f);
    glVertex2f(0.05f, 0.42f);
    glEnd();

    // shirt
    glColor3f(0.75f, 0.70f, 0.0f);
    drawQuad(-0.15f, 0.10f, 0.15f, 0.35f);

    glBegin(GL_TRIANGLES);
    glVertex2f(-0.15f, 0.35f);
    glVertex2f(-0.15f, 0.22f);
    glVertex2f(-0.25f, 0.25f);

    glVertex2f(0.15f, 0.35f);
    glVertex2f(0.15f, 0.22f);
    glVertex2f(0.25f, 0.25f);
    glEnd();

    // shorts
    glColor3f(0.45f, 0.58f, 0.78f);
    drawQuad(-0.15f, -0.15f, -0.02f, 0.10f);
    drawQuad(0.02f, -0.15f, 0.15f, 0.10f);
    drawQuad(-0.15f, 0.02f, 0.15f, 0.10f);

    // arms
    glColor3f(0.55f, 0.47f, 0.25f);
    drawQuad(-0.18f, 0.10f, -0.14f, 0.25f);
    drawFilledCircle(-0.16f, 0.08f, 0.045f);

    drawQuad(0.14f, 0.10f, 0.18f, 0.25f);
    drawFilledCircle(0.16f, 0.08f, 0.045f);

    // legs
    drawQuad(-0.12f, -0.30f, -0.05f, -0.15f);
    drawQuad(0.05f, -0.30f, 0.12f, -0.15f);

    // shoes
    glColor3f(0.75f, 0.70f, 0.0f);
    drawFilledCircle(-0.085f, -0.30f, 0.04f);
    drawFilledCircle(0.085f, -0.30f, 0.04f);

    glColor3f(0.20f, 0.05f, 0.0f);
    drawQuad(-0.13f, -0.36f, -0.04f, -0.32f);
    drawQuad(0.04f, -0.36f, 0.13f, -0.32f);

    glPopMatrix();
}

/**
 * draws the cat character used in the third scene.
 *
 * @param x x position of the cat.
 * @param y y position of the cat.
 * @param scale size multiplier for the cat.
 * @return nothing, it draws the full cat object.
 */
void drawCat(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // body
    glColor3f(0.0f, 0.0f, 0.0f);
    glBegin(GL_POLYGON);
    for (int i = 0; i < 360; i++) {
        float rad = i * 3.14159f / 180.0f;
        glVertex2f(cos(rad) * 0.28f, -0.15f + sin(rad) * 0.35f);
    }
    glEnd();

    // Head
    drawFilledCircle(0.0f, 0.15f, 0.22f);

    // Face fluff
    glBegin(GL_TRIANGLES);
    glVertex2f(-0.20f, 0.18f);
    glVertex2f(-0.28f, 0.15f);
    glVertex2f(-0.20f, 0.12f);

    glVertex2f(0.20f, 0.18f);
    glVertex2f(0.28f, 0.15f);
    glVertex2f(0.20f, 0.12f);
    glEnd();

    // Ears
    glBegin(GL_TRIANGLES);
    glVertex2f(-0.20f, 0.25f);
    glVertex2f(-0.05f, 0.30f);
    glVertex2f(-0.18f, 0.45f);

    glVertex2f(0.20f, 0.25f);
    glVertex2f(0.05f, 0.30f);
    glVertex2f(0.18f, 0.45f);
    glEnd();

    // Inner ears
    glColor3f(0.95f, 0.65f, 0.75f);
    glBegin(GL_TRIANGLES);
    glVertex2f(-0.18f, 0.28f);
    glVertex2f(-0.08f, 0.31f);
    glVertex2f(-0.16f, 0.41f);

    glVertex2f(0.18f, 0.28f);
    glVertex2f(0.08f, 0.31f);
    glVertex2f(0.16f, 0.41f);
    glEnd();

    // eyes
    glColor3f(0.70f, 0.90f, 1.0f);
    drawFilledCircle(-0.08f, 0.18f, 0.03f);
    drawFilledCircle(0.08f, 0.18f, 0.03f);

    // Nose
    glColor3f(0.95f, 0.65f, 0.75f);
    glBegin(GL_TRIANGLES);
    glVertex2f(-0.02f, 0.14f);
    glVertex2f(0.02f, 0.14f);
    glVertex2f(0.0f, 0.11f);
    glEnd();

    // mouth
    glColor3f(0.50f, 0.50f, 0.50f);
    glLineWidth(1.5f);
    glBegin(GL_LINE_STRIP);
    glVertex2f(-0.04f, 0.10f);
    glVertex2f(-0.02f, 0.08f);
    glVertex2f(0.0f, 0.10f);
    glVertex2f(0.02f, 0.08f);
    glVertex2f(0.04f, 0.10f);
    glEnd();

    // Whiskers
    glLineWidth(1.0f);
    drawLine(-0.15f, 0.15f, -0.35f, 0.22f);
    drawLine(-0.15f, 0.12f, -0.38f, 0.12f);
    drawLine(-0.15f, 0.09f, -0.35f, 0.02f);

    drawLine(0.15f, 0.15f, 0.35f, 0.22f);
    drawLine(0.15f, 0.12f, 0.38f, 0.12f);
    drawLine(0.15f, 0.09f, 0.35f, 0.02f);

    // legs
    glColor3f(0.0f, 0.0f, 0.0f);
    drawQuad(-0.09f, -0.52f, -0.03f, -0.20f);
    drawQuad(0.03f, -0.52f, 0.09f, -0.20f);

    // paw toes
    glColor3f(0.95f, 0.65f, 0.75f);
    drawFilledCircle(-0.08f, -0.54f, 0.015f);
    drawFilledCircle(-0.06f, -0.55f, 0.015f);
    drawFilledCircle(-0.04f, -0.54f, 0.015f);

    drawFilledCircle(0.08f, -0.54f, 0.015f);
    drawFilledCircle(0.06f, -0.55f, 0.015f);
    drawFilledCircle(0.04f, -0.54f, 0.015f);

    glPopMatrix();
}

/**
 * draws the mysterious girl character used in the ending scenes.
 *
 * @param x x position of the mysterious girl.
 * @param y y position of the mysterious girl.
 * @param scale size multiplier for the mysterious girl.
 * @return nothing, it draws the full character.
 */
void drawMysteriousGirl(float x, float y, float scale)
{
    glPushMatrix();
    glTranslatef(x, y, 0.0f);
    glScalef(scale, scale, 1.0f);

    // legs
    glColor3f(0.55f, 0.38f, 0.24f);
    drawQuad(-0.05f, -0.45f, -0.02f, -0.10f);
    drawQuad(0.02f, -0.45f, 0.05f, -0.10f);

    // shoes
    glColor3f(0.15f, 0.0f, 0.0f);
    drawQuad(-0.07f, -0.48f, -0.01f, -0.45f);
    drawQuad(0.01f, -0.48f, 0.07f, -0.45f);

    glColor3f(0.22f, 0.05f, 0.47f);
    drawFilledCircle(-0.04f, -0.45f, 0.025f);
    drawFilledCircle(0.04f, -0.45f, 0.025f);

    // dress skirt
    glColor3f(0.22f, 0.05f, 0.47f);
    glBegin(GL_POLYGON);
    glVertex2f(-0.28f, -0.38f);
    glVertex2f(0.28f, -0.38f);
    glVertex2f(0.12f, -0.10f);
    glVertex2f(-0.12f, -0.10f);
    glEnd();

    // dress top
    drawQuad(-0.18f, 0.02f, 0.18f, 0.15f);
    drawQuad(-0.12f, -0.10f, 0.12f, 0.02f);

    // arms
    glColor3f(0.55f, 0.38f, 0.24f);
    drawQuad(-0.14f, -0.15f, -0.10f, 0.02f);
    drawQuad(0.10f, -0.15f, 0.14f, 0.02f);
    drawFilledCircle(-0.12f, -0.18f, 0.035f);
    drawFilledCircle(0.12f, -0.18f, 0.035f);

    // neck
    drawQuad(-0.02f, 0.15f, 0.02f, 0.20f);

    // face
    drawQuad(-0.10f, 0.20f, 0.10f, 0.35f);

    // eyes
    glColor3f(0.0f, 0.0f, 0.0f);
    drawFilledCircle(-0.04f, 0.30f, 0.015f);
    drawFilledCircle(0.04f, 0.30f, 0.015f);

    // mouth
    drawQuad(-0.05f, 0.24f, 0.05f, 0.26f);

    // hair
    glColor3f(1.0f, 0.80f, 0.0f);

    // top
    drawQuad(-0.12f, 0.35f, 0.12f, 0.48f);

    // left piece
    glBegin(GL_POLYGON);
    glVertex2f(-0.28f, 0.22f);
    glVertex2f(-0.10f, 0.22f);
    glVertex2f(-0.10f, 0.48f);
    glVertex2f(-0.25f, 0.48f);
    glEnd();

    // right piece
    glBegin(GL_POLYGON);
    glVertex2f(0.10f, 0.22f);
    glVertex2f(0.28f, 0.22f);
    glVertex2f(0.25f, 0.48f);
    glVertex2f(0.10f, 0.48f);
    glEnd();

    glPopMatrix();
}

// ---------- scenes ----------

/**
 * controls and draws scene 1, where the girl chooses whether to help the grandma.
 *
 * @return nothing, it updates scene 1 animation and draws its objects.
 */
void Scene1()
{
    // sky, sidewalk, road
    drawRectWithOutline(-1.0f, 0.10f, 1.0f, 1.0f,
        0.68f, 0.85f, 0.90f);

    drawRectWithOutline(-1.0f, -1.0f, -0.20f, 0.10f,
        0.75f, 0.75f, 0.75f);

    drawTexturedRect(-0.20f, -1.0f, 1.0f, 0.10f, myTexture2);

    // crosswalk
    for (float i = -0.05f; i < 0.85f; i += 0.20f) {
        drawRectWithOutline(i, -0.73f, i + 0.10f, -0.25f,
            1.0f, 1.0f, 1.0f);
    }

    drawSun(-0.70f, 0.70f, 1.0f);
    drawCloud(-0.35f, 0.80f, 0.80f);
    drawCloud(0.65f, 0.62f, 0.75f);

    if (sceneState == 0)
    {
        // animation using translation
        scene1CarMoveY -= 0.0004f;

        if (scene1GirlMoveX < 0.55f)
            scene1GirlMoveX += 0.00015f;

        glPushMatrix();
        glTranslatef(scene1GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.45f);
        glPopMatrix();

        drawGrandma(-0.25f, -0.45f, 0.38f);

        // source: https://learn.microsoft.com/en-us/previous-versions/dd743680(v=vs.85)
        // source: https://www.youtube.com/watch?v=HrgzpIyjlxs
        // source: https://www.freesoundslibrary.com/page-turning-sound-effect/#google_vignette
        if (!carSoundPlayed)
        {
            PlaySound(TEXT("C:\\sounds\\car.wav"), NULL, SND_ASYNC);
            carSoundPlayed = true;
        }

        glPushMatrix();
        glTranslatef(0.0f, scene1CarMoveY, 0.0f);
        drawCar(0.35f, 0.20f, 1.0f);
        glPopMatrix();



        if (scene1GirlMoveX >= 0.55f && scene1CarMoveY <= -1.60f)
        {
            scene1GirlMoveX = 0.55f;
            sceneState = 1;
        }
    }

    else if (sceneState == 1)
    {
        glPushMatrix();
        glTranslatef(scene1GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.45f);
        glPopMatrix();

        drawGrandma(-0.25f, -0.45f, 0.38f);

        glColor3f(0, 0, 0);
        drawDialogueBox(-0.90f, 0.60f, 0.90f, 0.88f,
            "GRANDMA: Hi sweetie, could you help me",
            "cross the road please?");
    }

    else if (sceneState == 2)
    {
        glPushMatrix();
        glTranslatef(scene1GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.45f);
        glPopMatrix();

        drawGrandma(-0.25f, -0.45f, 0.38f);

        drawChoiceButtons("Ignore the Grandma", "Help the Grandma");
    }

    else if (sceneState == 3)
    {
        scene1GirlMoveX += 0.00015f;

        if (grandmaHelped)
            scene1GrandmaMoveX += 0.00015f;

        glPushMatrix();
        glTranslatef(scene1GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.45f);
        glPopMatrix();

        glPushMatrix();
        glTranslatef(scene1GrandmaMoveX, 0.0f, 0.0f);
        drawGrandma(-0.25f, -0.45f, 0.38f);
        glPopMatrix();

        if (grandmaHelped)
            drawDialogueBox(-0.90f, 0.70f, 0.90f, 0.88f,
                "YOU: Sure!!",
                NULL);
        else
            drawDialogueBox(-0.90f, 0.70f, 0.90f, 0.88f,
                "YOU: NOOO!!",
                NULL);

        if (scene1GirlMoveX >= 1.75f)
        {
            scene = 2;
            sceneState = 0;

            scene1GirlMoveX = 0.0f;
            scene1GrandmaMoveX = 0.0f;
            scene1CarMoveY = 0.0f;
        }
    }
}

/**
 * controls and draws scene 2, where the girl chooses whether to help the boy.
 *
 * @return nothing, it updates scene 2 animation and draws its objects.
 */
void Scene2()
{
    // sky and grass
    drawRectWithOutline(-1.0f, 0.0f, 1.0f, 1.0f,
        0.68f, 0.85f, 0.90f);

    drawRectWithOutline(-1.0f, -1.0f, 1.0f, 0.0f,
        0.48f, 0.98f, 0.0f);

    // sun
    drawSun(-0.78f, 0.75f, 0.85f);

    // clouds
    drawCloud(0.45f, 0.80f, 0.85f);
    drawCloud(-0.95f, 0.35f, 0.65f);

    // trees - same idea and sizes as friend's code
    drawTree(-0.75f, 0.0f, 0.90f,
        0.25f, 0.45f, 0.0f);

    drawTree(0.75f, 0.0f, 0.80f,
        0.25f, 0.45f, 0.0f);

    drawTree(0.0f, -0.20f, 1.70f,
        0.65f, 0.95f, 0.10f);

    // football
    drawFootball(0.60f, -0.50f, 0.45f);

    if (sceneState == 0)
    {
        // balloon flies up using translate
        if (scene2BalloonMoveY < 0.85f)
            scene2BalloonMoveY += 0.00015f;

        // girl walks to the tree using translate
        if (scene2GirlMoveX < 0.90f)
            scene2GirlMoveX += 0.00015f;

        glPushMatrix();
        glTranslatef(0.0f, scene2BalloonMoveY, 0.0f);
        drawBalloon(0.20f, -0.45f, 1.0f);
        glPopMatrix();

        glPushMatrix();
        glTranslatef(scene2GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.42f);
        glPopMatrix();

        drawBoy(0.40f, -0.48f, 0.35f);

        if (scene2GirlMoveX >= 0.90f && scene2BalloonMoveY >= 0.85f)
        {
            scene2GirlMoveX = 0.90f;
            scene2BalloonMoveY = 0.85f;
            sceneState = 1;
        }
    }

    else if (sceneState == 1)
    {
        glPushMatrix();
        glTranslatef(0.0f, scene2BalloonMoveY, 0.0f);
        drawBalloon(0.20f, -0.45f, 1.0f);
        glPopMatrix();

        glPushMatrix();
        glTranslatef(scene2GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.42f);
        glPopMatrix();

        drawBoy(0.40f, -0.48f, 0.35f);

        // source: https://learn.microsoft.com/en-us/previous-versions/dd743680(v=vs.85)
        // source: https://www.youtube.com/watch?v=HrgzpIyjlxs
        // source: https://www.freesoundslibrary.com/page-turning-sound-effect/#google_vignette
        if (!cryPlayed)
        {
            PlaySound(TEXT("C:\\sounds\\crying.wav"), NULL, SND_ASYNC);
            cryPlayed = true;
        }

        drawDialogueBox(-0.90f, 0.60f, 0.90f, 0.88f,
            "BOY: *crying* My balloon...",
            "It's stuck in the tree, please help me!");
    }

    else if (sceneState == 2)
    {
        glPushMatrix();
        glTranslatef(0.0f, scene2BalloonMoveY, 0.0f);
        drawBalloon(0.20f, -0.45f, 1.0f);
        glPopMatrix();

        glPushMatrix();
        glTranslatef(scene2GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.42f);
        glPopMatrix();

        drawBoy(0.40f, -0.48f, 0.35f);

        drawChoiceButtons("Laugh at the Kid", "Help the Kid");
    }

    else if (sceneState == 3)
    {
        // good choice: help
        if (kidHelped)
        {
            // step 0: jump toward balloon
            if (scene2HelpStep == 0)
            {
                if (scene2GirlJumpY < 0.25f)
                    scene2GirlJumpY += 0.0003f;
                else
                    scene2HelpStep = 1; // now she reached the balloon
            }

            // step 1: move to boy
            else if (scene2HelpStep == 1)
            {
                if (scene2GiveBalloonX < 0.35f)
                    scene2GiveBalloonX += 0.0002f;
                else
                    scene2HelpStep = 2;
            }

            // step 2: leave
            else if (scene2HelpStep == 2)
            {
                scene2GirlMoveX += 0.00015f;
            }

            // draw girl
            glPushMatrix();
            glTranslatef(scene2GirlMoveX + scene2GiveBalloonX, scene2GirlJumpY, 0.0f);
            drawMainGirl(-0.95f, -0.45f, 0.42f);
            glPopMatrix();

            // draw boy
            drawBoy(0.40f, -0.48f, 0.35f);

            // balloon behavior
            if (scene2HelpStep == 0 && scene2GirlJumpY < 0.25f)
            {
                // still in tree
                glPushMatrix();
                glTranslatef(0.0f, scene2BalloonMoveY, 0.0f);
                drawBalloon(0.20f, -0.45f, 1.0f);
                glPopMatrix();
                
            }
            else if (scene2HelpStep == 0 || scene2HelpStep == 1)
            {
                // with girl AFTER she reaches it
                glPushMatrix();
                glTranslatef(scene2GirlMoveX + scene2GiveBalloonX, scene2GirlJumpY, 0.0f);
                drawBalloon(-0.83f, -0.10f, 1.0f);
                glPopMatrix();

             
            }
            else
            {
                // with boy
                drawBalloon(0.48f, -0.20f, 1.0f);

                drawDialogueBox(-0.90f, 0.70f, 0.90f, 0.88f,
                    "YOU: Here you go!",
                    NULL);
            }

            // go to next scene
            if (scene2GirlMoveX >= 1.75f)
            {
                scene = 3;
                sceneState = 0;

                scene2GirlMoveX = 0.0f;
                scene2BalloonMoveY = 0.0f;
                scene2GirlJumpY = 0.0f;
                scene2GiveBalloonX = 0.0f;
                scene2HelpStep = 0;
            }
        }

        // bad choice: ignore
        else
        {
            scene2GirlMoveX += 0.0002f;

            // balloon stays in tree
            glPushMatrix();
            glTranslatef(0.0f, scene2BalloonMoveY, 0.0f);
            drawBalloon(0.20f, -0.45f, 1.0f);
            glPopMatrix();

            // girl walking
            glPushMatrix();
            glTranslatef(scene2GirlMoveX, 0.0f, 0.0f);
            drawMainGirl(-0.95f, -0.45f, 0.42f);
            glPopMatrix();

            drawBoy(0.40f, -0.48f, 0.35f);

            drawDialogueBox(-0.90f, 0.70f, 0.90f, 0.88f,
                "YOU: Hahaha, such a loser!",
                NULL);

            if (scene2GirlMoveX >= 1.75f)
            {
                scene = 3;
                sceneState = 0;

                scene2GirlMoveX = 0.0f;
                scene2BalloonMoveY = 0.0f;
            }
        }
    }
}

/**
 * controls and draws scene 3, where the girl chooses how to treat the cat.
 *
 * @return nothing, it updates scene 3 animation and draws its objects.
 */
void Scene3()
{
    // sky
    drawRectWithOutline(-1.0f, -0.10f, 1.0f, 1.0f,
        0.68f, 0.85f, 0.90f);

    // grass and path
    drawRectWithOutline(-1.0f, -1.0f, -0.50f, -0.10f,
        0.48f, 0.98f, 0.0f);

    drawRectWithOutline(-0.50f, -1.0f, 1.0f, -0.10f,
        0.94f, 0.90f, 0.75f);

    drawSun(0.80f, 0.70f, 1.0f);
    drawCloud(-0.35f, 0.85f, 0.75f);
    drawCloud(0.45f, 0.70f, 0.65f);

    drawTree(-0.85f, -0.40f, 1.80f,
        0.65f, 0.95f, 0.10f);

    drawBench();

    if (sceneState == 0)
    {
        // girl walks to bench
        if (scene3GirlMoveX < 0.60f)
            scene3GirlMoveX += 0.0001f;

        // draw girl
        glPushMatrix();
        glTranslatef(scene3GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.42f);
        glPopMatrix();

        // cat on the bench (initial)
        drawCat(0.25f, 0.10f, 0.22f);

        if (scene3GirlMoveX >= 0.60f)
        {
            sceneState = 1;
        }
    }

    else if (sceneState == 1)
    {
        // cat moves down to side
        if (scene3CatMoveY > -0.30f)
            scene3CatMoveY -= 0.00015f;

        // draw girl
        glPushMatrix();
        glTranslatef(scene3GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.42f);
        glPopMatrix();

        // source: https://learn.microsoft.com/en-us/previous-versions/dd743680(v=vs.85)
        // source: https://www.youtube.com/watch?v=HrgzpIyjlxs
        // source: https://www.freesoundslibrary.com/page-turning-sound-effect/#google_vignette
        if (!meowPlayed)
        {

            PlaySound(TEXT("C:\\sounds\\meow.wav"), NULL, SND_ASYNC);
            meowPlayed = true;
        }
        // draw cat (moving)
        glPushMatrix();
        glTranslatef(scene3CatMoveX, scene3CatMoveY, 0.0f);
        drawCat(0.25f, 0.10f, 0.22f);
        glPopMatrix();

        if (scene3CatMoveY <= -0.30f)
        {
            sceneState = 2;
        }
    }

    else if (sceneState == 2)
    {
        glPushMatrix();
        glTranslatef(scene3GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.45f, 0.42f);
        glPopMatrix();

        drawCat(0.25f, -0.20f, 0.22f);
        drawChoiceButtons("Kick the Cat", "Sit Down");
    }

    else if (sceneState == 3)
    {
        if (catSatDown)
        {
            // sit down result
            glPushMatrix();
            glTranslatef(1.15f, 0.50f, 0.0f);
            drawMainGirl(-0.95f, -0.45f, 0.42f);
            glPopMatrix();

            drawCat(0.25f, -0.20f, 0.22f);

            drawDialogueBox(-0.90f, 0.70f, 0.90f, 0.88f, "YOU: I'll sit down.", NULL);

            if (waitForSeconds(5.0f))
            {
                if (score >= 1)
                    scene = 4;
                else
                    scene = 5;

                sceneState = 0;
                scene3Step = 0;
                scene3GirlMoveX = 0.0f;
                scene3CatMoveX = 0.0f;
                scene3CatMoveY = 0.0f;
            }
        }
        else if (!catSatDown)
        {
            // kick result
            if (scene3Step == 0)
            {
                if (scene3GirlMoveX < 0.80f)
                    scene3GirlMoveX += 0.00015f;
                else
                    scene3Step = 1;
            }
            else if (scene3Step == 1)
            {
                scene3CatMoveX += 0.0006f;
                scene3CatMoveY += 0.0004f;
            }

            glPushMatrix();
            glTranslatef(scene3GirlMoveX, 0.0f, 0.0f);
            drawMainGirl(-0.95f, -0.45f, 0.42f);
            glPopMatrix();

            glPushMatrix();
            glTranslatef(scene3CatMoveX, scene3CatMoveY, 0.0f);
            glRotatef(scene3CatMoveX * 500.0f, 0.0f, 0.0f, 1.0f);
            drawCat(0.25f, -0.20f, 0.22f);
            glPopMatrix();

            drawDialogueBox(-0.90f, 0.70f, 0.90f, 0.88f, "YOU: Hahaha!", NULL);

            if (scene3CatMoveX >= 1.50f)
            {
                if (score >= 1)
                    scene = 4;
                else
                    scene = 5;

                sceneState = 0;
                scene3Step = 0;
                scene3GirlMoveX = 0.0f;
                scene3CatMoveX = 0.0f;
                scene3CatMoveY = 0.0f;
            }
        }
    }
}

/**
 * controls and draws the good ending scene.
 *
 * @return nothing, it updates the good ending animation and draws it.
 */
void Scene4()
{
    // sky and road layers
    drawRectWithOutline(-1.0f, -0.10f, 1.0f, 1.0f,
        0.68f, 0.85f, 0.90f);

    drawRectWithOutline(-1.0f, -0.55f, 1.0f, -0.10f,
        0.75f, 0.75f, 0.75f);

    drawRectWithOutline(-1.0f, -1.0f, 1.0f, -0.55f,
        0.45f, 0.45f, 0.45f);

    // house wall
    drawTexturedRect(-1.0f, -0.10f, -0.05f, 1.0f, myTexture1);

    // door
    drawRectWithOutline(-0.75f, -0.10f, -0.45f, 0.50f,
        0.45f, 0.30f, 0.20f);

    glColor3f(1.0f, 0.75f, 0.0f);
    drawFilledCircle(-0.50f, 0.20f, 0.03f);

    // garden view
    drawRectWithOutline(-0.05f, -0.10f, 1.0f, 0.30f,
        0.48f, 0.98f, 0.0f);

    // sun behind cloud
    drawSun(0.22f, 0.78f, 0.65f);

    // cloud in front of sun
    drawCloud(0.30f, 0.75f, 0.80f);

    // tree
    drawTree(0.75f, 0.15f, 1.20f,
        0.45f, 0.65f, 0.15f);

    // fence
    for (float i = -0.05f; i < 1.0f; i += 0.10f) {
        drawRectWithOutline(i, -0.10f, i + 0.05f, 0.15f,
            0.60f, 0.40f, 0.30f);
    }

    drawRectWithOutline(-0.05f, 0.00f, 1.0f, 0.03f,
        0.50f, 0.30f, 0.20f);

    drawRectWithOutline(-0.05f, 0.08f, 1.0f, 0.11f,
        0.50f, 0.30f, 0.20f);

    // water puddle
    drawWaterPuddle(-0.02f, -0.35f, 1.0f);

    if (sceneState == 0)
    {
        // girl walks to water
        if (scene4GirlMoveX < 0.88f)
            scene4GirlMoveX += 0.00015f;
        else
            sceneState = 1;

        glPushMatrix();
        glTranslatef(scene4GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.20f, 0.42f);
        glPopMatrix();


    }

    else if (sceneState == 1)
    {
        // girl falls
        glPushMatrix();
        glTranslatef(-0.07f, -0.28f, 0.0f);
        glRotatef(-90.0f, 0.0f, 0.0f, 1.0f);
        drawMainGirl(0.0f, 0.0f, 0.42f);
        glPopMatrix();

        drawDialogueBox(-0.90f, 0.70f, 0.90f, 0.88f, "YOU: Ouch!!" ,NULL);

        // mysterious girl enters
        if (scene4MysteryMoveX > -0.95f)
            scene4MysteryMoveX -= 0.00015f;
        else
            sceneState = 2;

        glPushMatrix();
        glTranslatef(scene4MysteryMoveX, 0.0f, 0.0f);
        drawMysteriousGirl(1.25f, -0.20f, 0.45f);
        glPopMatrix();
    }

    else if (sceneState == 2)
    {
        // Girl standing after help
        drawMainGirl(-0.07f, -0.28f, 0.42f);

        glPushMatrix();
        glTranslatef(scene4MysteryMoveX, 0.0f, 0.0f);
        drawMysteriousGirl(1.25f, -0.20f, 0.45f);
        glPopMatrix();

        drawDialogueBox(-0.90f, 0.60f, 0.90f, 0.88f, "MYSTERIOUS GIRL: Are you okay?",
            "YOU: YES! Thanks for helping me stand up.");
        

        if (waitForSeconds(8.0f))
        {
            scene = 6;
        }
    }
}

/**
 * controls and draws the bad ending scene.
 *
 * @return nothing, it updates the bad ending animation and draws it.
 */
void Scene5()
{
    // sky, grass, path
    drawRectWithOutline(-1.0f, 0.30f, 1.0f, 1.0f,
        0.68f, 0.85f, 0.90f);

    drawRectWithOutline(-1.0f, -0.10f, 1.0f, 0.30f,
        0.48f, 0.98f, 0.0f);

    drawRectWithOutline(-1.0f, -0.90f, 1.0f, -0.10f,
        0.94f, 0.90f, 0.75f);

    drawRectWithOutline(-1.0f, -1.0f, 1.0f, -0.90f,
        0.48f, 0.98f, 0.0f);

    // sun first, clouds appear in front of it
    drawSun(-0.10f, 0.85f, 0.70f);

    // clouds in front of the sun and behind the trees
    drawCloud(-0.05f, 0.88f, 0.75f);
    drawCloud(0.72f, 0.88f, 0.60f);

    // trees after clouds, so trees appear in front of clouds
    drawTree(-0.85f, 0.30f, 0.90f,
        0.30f, 0.50f, 0.0f);

    drawTree(-0.55f, 0.22f, 1.40f,
        0.60f, 0.90f, 0.10f);

    drawTree(0.15f, 0.30f, 1.0f,
        0.40f, 0.70f, 0.0f);

    drawTree(0.45f, 0.22f, 1.50f,
        0.60f, 0.90f, 0.10f);

    drawTree(0.95f, 0.30f, 1.0f,
        0.30f, 0.50f, 0.0f);

    // old garbage bin shape
    drawTrashCan(-0.25f, 0.08f, 1.0f);

    // 4 garbage pieces around the bin
    drawTrashPiece(-0.43f, -0.08f, 0.70f,
        0.10f, 0.10f, 0.85f);

    drawTrashPiece(-0.15f, -0.12f, 0.70f,
        0.95f, 0.85f, 0.10f);

    drawTrashPiece(-0.35f, -0.25f, 0.65f,
        0.10f, 0.70f, 0.20f);

    drawTrashPiece(-0.12f, -0.30f, 0.65f,
        0.70f, 0.20f, 0.70f);

    // garbage in the middle of the sidewalk/path
    drawTrashPiece(0.05f, -0.55f, 0.85f,
        0.85f, 0.05f, 0.08f);

    if (sceneState == 0)
    {
        // girl walks to the trash piece
        if (scene5GirlMoveX < 1.00f)
            scene5GirlMoveX += 0.00015f;
        else
            sceneState = 1;

        glPushMatrix();
        glTranslatef(scene5GirlMoveX, 0.0f, 0.0f);
        drawMainGirl(-0.95f, -0.40f, 0.42f);
        glPopMatrix();
    }

    else if (sceneState == 1)
    {
        // girl falls because of trash
        glPushMatrix();
        glTranslatef(0.05f, -0.55f, 0.0f);
        glRotatef(-90.0f, 0.0f, 0.0f, 1.0f);
        drawMainGirl(0.0f, 0.0f, 0.42f);
        glPopMatrix();

        drawDialogueBox(-0.95f, 0.60f, 0.95f, 0.88f, "YOU: Ouch!!", "MYSTERIOUS GIRL: Haha, watch your steps!");

        // mysterious girl enters and keeps walking
        scene5MysteryMoveX -= 0.0002f;

        glPushMatrix();
        glTranslatef(scene5MysteryMoveX, 0.0f, 0.0f);
        drawMysteriousGirl(1.25f, -0.20f, 0.45f);
        glPopMatrix();

        

        if (scene5MysteryMoveX <= -2.45f)
            sceneState = 2;
    }

    else if (sceneState == 2)
    {
        // girl still fallen, realizing what happened
        glPushMatrix();
        glTranslatef(0.05f, -0.55f, 0.0f);
        glRotatef(-90.0f, 0.0f, 0.0f, 1.0f);
        drawMainGirl(0.0f, 0.0f, 0.42f);
        glPopMatrix();

        drawDialogueBox(-0.90f, 0.60f, 0.90f, 0.88f, "YOU: This happened because of",
            "all my bad actions.");
        

        if (waitForSeconds(8.0f))
        {
            scene = 6;
        }
    }
}

/**
 * draws the final message screen after the ending.
 *
 * @return nothing, it shows the final story message.
 */
void Scene6()
{
    glColor3f(0.0f, 0.0f, 0.0f);
    drawQuad(-1.0f, -1.0f, 1.0f, 1.0f);

    glColor3f(1.0f, 1.0f, 1.0f);
    drawText(-0.18f, 0.05f, "Be Kind");
}

/**
 * handles mouse clicks on the story choice buttons.
 *
 * @param button mouse button that was clicked.
 * @param state tells if the button was pressed or released.
 * @param x mouse x position in window coordinates.
 * @param y mouse y position in window coordinates.
 * @return nothing, it updates the story state based on the clicked choice.
 */
static

/**
 * handles mouse clicks on the story choice buttons.
 *
 * @param button mouse button that was clicked.
 * @param state tells if the button was pressed or released.
 * @param x mouse x position in window coordinates.
 * @param y mouse y position in window coordinates.
 * @return nothing, it updates the story state based on the clicked choice.
 */
    void mouse(int button, int state, int x, int y)
{
    if (button == GLUT_LEFT_BUTTON && state == GLUT_UP)
    {
        float mx = (2.0f * x / win_width) - 1.0f;
        float my = 1.0f - (2.0f * y / win_hight);

        if (sceneState == 2)
        {
            // Bad button
            if (mx >= badBtnX1 && mx <= badBtnX2 &&
                my >= btnY1 && my <= btnY2)
            {
                score--;

                if (scene == 1)
                    grandmaHelped = false;
                else if (scene == 2)
                    kidHelped = false;
                else if (scene == 3)
                    catSatDown = false;

                sceneState = 3;
            }

            // Good button
            else if (mx >= goodBtnX1 && mx <= goodBtnX2 &&
                my >= btnY1 && my <= btnY2)
            {
                score++;

                if (scene == 1)
                    grandmaHelped = true;
                else if (scene == 2)
                    kidHelped = true;
                else if (scene == 3)
                    catSatDown = true;

                sceneState = 3;
            }

            glutPostRedisplay();
        }
    }
}

/**
 * keeps the display refreshing so the animations can move.
 *
 * @return nothing, it asks GLUT to redraw the screen.
 */
static void play(void)
{
    glutPostRedisplay();
}

/**
 * handles keyboard input for moving through the story and quitting.
 *
 * @param keyPressed the keyboard key pressed by the user.
 * @param x mouse x position when the key was pressed.
 * @param y mouse y position when the key was pressed.
 * @return nothing, it changes scene states or exits the program.
 */
static

/**
 * handles keyboard input for moving through the story and quitting.
 *
 * @param keyPressed the keyboard key pressed by the user.
 * @param x mouse x position when the key was pressed.
 * @param y mouse y position when the key was pressed.
 * @return nothing, it changes scene states or exits the program.
 */
    void key(unsigned char keyPressed, int x, int y)
{
    switch (keyPressed) {

    case 'n':
    case 'N':
        if (sceneState == 1)
            sceneState = 2; // show buttons after dialogue
        break;

    case 'q':
    case 'Q':
        exit(0);
        break;

    default:
        fprintf(stderr, "\nKeyboard commands:\n\n"
            "n/N         - Continue dialogue\n"
            "q/Q  - Quit\n");
        break;
    }

    glutPostRedisplay();
}

/**
 * starts the background music using the Windows mci command.
 * source: https://learn.microsoft.com/en-us/windows/win32/multimedia/mcisendstring
 *
 * @return nothing, it plays the background music in a loop.
 */
void startBackgroundMusic()
{
    mciSendString(TEXT("open \"C:\\sounds\\music.wav\" alias bgm"), NULL, 0, NULL);
    mciSendString(TEXT("play bgm"), NULL, 0, NULL);
}

/**
 * prepares the OpenGL settings and loads the textures before the story starts.
 *
 * @return nothing, it sets the clear color, projection, blend mode, and textures.
 */
void init()
{
    glClearColor(0.8f, 0.9f, 1.0f, 1.0f);
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluOrtho2D(-1, 1, -1, 1); // default view

    glMatrixMode(GL_MODELVIEW);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

    glEnable(GL_TEXTURE_2D);

    myTexture1 = LoadTexture(image1Path, 5000, 3336); // brick wall
    myTexture2 = LoadTexture(image2Path, 2000, 3000); // road

    glBindTexture(GL_TEXTURE_2D, 0);
    glDisable(GL_TEXTURE_2D);

    startBackgroundMusic();

}

/**
 * updates the OpenGL viewport when the window size changes.
 *
 * @param new_width the new window width.
 * @param new_hight the new window height.
 * @return nothing, it refreshes the viewport and projection.
 */
void reshapeFunc(GLint new_width, GLint new_hight)
{
    glViewport(0, 0, new_width, new_hight);
    win_width = new_width;
    win_hight = new_hight;
}

// ---------- display ----------

/**
 * chooses which scene to draw based on the current scene number.
 *
 * @return nothing, it draws the current frame on the screen.
 */
void display()
{
    glClear(GL_COLOR_BUFFER_BIT);

    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();

    // source: https://stackoverflow.com/questions/20677023/change-scenes-in-game-opengl.com
    if (scene == 1)
        Scene1();

    else if (scene == 2)
        Scene2();

    else if (scene == 3)
        Scene3();

    else if (scene == 4)
        Scene4();

    else if (scene == 5)
        Scene5();

    else if (scene == 6)
        Scene6();

    glFlush();
    glutSwapBuffers();
}

// ---------- main ----------

/**
 * starts the GLUT program and connects all callbacks.
 *
 * @param argc number of command line arguments.
 * @param argv command line argument values.
 * @return zero when the program ends normally.
 */
int main(int argc, char** argv)
{

    glutInit(&argc, argv); // initialize GLUT
    glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE | GLUT_DEPTH); // use RGBA, double buffer, and depth buffer
    glutInitWindowSize(500, 500); // set the window's initial width and height
    glutInitWindowPosition(250, 50); // position the window's initial top-left corner
    glutCreateWindow("OpenGL_Project _ Be Kind"); // create a window with the given title

    init();

    glutIdleFunc(play);
    glutDisplayFunc(display);
    glutReshapeFunc(reshapeFunc);
    glutMouseFunc(mouse);
    glutKeyboardFunc(key);

    glutMainLoop(); // enter the main event loop

    return 0;
}

